// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/tiandoudou/serialization/user.proto

package com.tiantiandou.serialization;

public final class UserProto {
    private UserProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface UserOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.tiantiandou.serialization.User)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>required string name = 2;</code>
         */
        boolean hasName();

        /**
         * <code>required string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <code>required string name = 2;</code>
         */
        com.google.protobuf.ByteString
                getNameBytes();

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        java.util.List<com.tiantiandou.serialization.UserProto.User.Address>
                getAddressesList();

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        com.tiantiandou.serialization.UserProto.User.Address getAddresses(int index);

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        int getAddressesCount();

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        java.util.List<? extends com.tiantiandou.serialization.UserProto.User.AddressOrBuilder>
                getAddressesOrBuilderList();

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        com.tiantiandou.serialization.UserProto.User.AddressOrBuilder getAddressesOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code com.tiantiandou.serialization.User}
     */
    public static final class User extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:com.tiantiandou.serialization.User)
            UserOrBuilder {
        // Use User.newBuilder() to construct.
        private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private User(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final User defaultInstance;

        public static User getDefaultInstance() {
            return defaultInstance;
        }

        public User getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
                getUnknownFields() {
            return this.unknownFields;
        }

        private User(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            name_ = bs;
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                addresses_ = new java.util.ArrayList<com.tiantiandou.serialization.UserProto.User.Address>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            addresses_.add(input.readMessage(
                                    com.tiantiandou.serialization.UserProto.User.Address.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    addresses_ = java.util.Collections.unmodifiableList(addresses_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.tiantiandou.serialization.UserProto.User.class,
                            com.tiantiandou.serialization.UserProto.User.Builder.class);
        }

        public static com.google.protobuf.Parser<User> PARSER =
                new com.google.protobuf.AbstractParser<User>() {
                    public User parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                        return new User(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<User> getParserForType() {
            return PARSER;
        }

        public interface AddressOrBuilder extends
                // @@protoc_insertion_point(interface_extends:com.tiantiandou.serialization.User.Address)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>optional int32 id = 1;</code>
             */
            boolean hasId();

            /**
             * <code>optional int32 id = 1;</code>
             */
            int getId();

            /**
             * <code>repeated string address_name = 2;</code>
             */
            com.google.protobuf.ProtocolStringList
                    getAddressNameList();

            /**
             * <code>repeated string address_name = 2;</code>
             */
            int getAddressNameCount();

            /**
             * <code>repeated string address_name = 2;</code>
             */
            java.lang.String getAddressName(int index);

            /**
             * <code>repeated string address_name = 2;</code>
             */
            com.google.protobuf.ByteString
                    getAddressNameBytes(int index);

            /**
             * <code>required bytes data = 3;</code>
             */
            boolean hasData();

            /**
             * <code>required bytes data = 3;</code>
             */
            com.google.protobuf.ByteString getData();
        }

        /**
         * Protobuf type {@code com.tiantiandou.serialization.User.Address}
         */
        public static final class Address extends
                com.google.protobuf.GeneratedMessage implements
                // @@protoc_insertion_point(message_implements:com.tiantiandou.serialization.User.Address)
                AddressOrBuilder {
            // Use Address.newBuilder() to construct.
            private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }

            private Address(boolean noInit) {
                this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
            }

            private static final Address defaultInstance;

            public static Address getDefaultInstance() {
                return defaultInstance;
            }

            public Address getDefaultInstanceForType() {
                return defaultInstance;
            }

            private final com.google.protobuf.UnknownFieldSet unknownFields;

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
                    getUnknownFields() {
                return this.unknownFields;
            }

            private Address(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 8: {
                                bitField0_ |= 0x00000001;
                                id_ = input.readInt32();
                                break;
                            }
                            case 18: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                    addressName_ = new com.google.protobuf.LazyStringArrayList();
                                    mutable_bitField0_ |= 0x00000002;
                                }
                                addressName_.add(bs);
                                break;
                            }
                            case 26: {
                                bitField0_ |= 0x00000002;
                                data_ = input.readBytes();
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(this);
                } finally {
                    if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                        addressName_ = addressName_.getUnmodifiableView();
                    }
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_Address_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_Address_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.tiantiandou.serialization.UserProto.User.Address.class,
                                com.tiantiandou.serialization.UserProto.User.Address.Builder.class);
            }

            public static com.google.protobuf.Parser<Address> PARSER =
                    new com.google.protobuf.AbstractParser<Address>() {
                        public Address parsePartialFrom(
                                com.google.protobuf.CodedInputStream input,
                                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                            return new Address(input, extensionRegistry);
                        }
                    };

            @java.lang.Override
            public com.google.protobuf.Parser<Address> getParserForType() {
                return PARSER;
            }

            private int bitField0_;
            public static final int ID_FIELD_NUMBER = 1;
            private int id_;

            /**
             * <code>optional int32 id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            public static final int ADDRESS_NAME_FIELD_NUMBER = 2;
            private com.google.protobuf.LazyStringList addressName_;

            /**
             * <code>repeated string address_name = 2;</code>
             */
            public com.google.protobuf.ProtocolStringList
                    getAddressNameList() {
                return addressName_;
            }

            /**
             * <code>repeated string address_name = 2;</code>
             */
            public int getAddressNameCount() {
                return addressName_.size();
            }

            /**
             * <code>repeated string address_name = 2;</code>
             */
            public java.lang.String getAddressName(int index) {
                return addressName_.get(index);
            }

            /**
             * <code>repeated string address_name = 2;</code>
             */
            public com.google.protobuf.ByteString
                    getAddressNameBytes(int index) {
                return addressName_.getByteString(index);
            }

            public static final int DATA_FIELD_NUMBER = 3;
            private com.google.protobuf.ByteString data_;

            /**
             * <code>required bytes data = 3;</code>
             */
            public boolean hasData() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required bytes data = 3;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            private void initFields() {
                id_ = 0;
                addressName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                data_ = com.google.protobuf.ByteString.EMPTY;
            }

            private byte memoizedIsInitialized = -1;

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1)
                    return true;
                if (isInitialized == 0)
                    return false;

                if (!hasData()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeInt32(1, id_);
                }
                for (int i = 0; i < addressName_.size(); i++) {
                    output.writeBytes(2, addressName_.getByteString(i));
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeBytes(3, data_);
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;

            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1)
                    return size;

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(1, id_);
                }
                {
                    int dataSize = 0;
                    for (int i = 0; i < addressName_.size(); i++) {
                        dataSize += com.google.protobuf.CodedOutputStream
                                .computeBytesSizeNoTag(addressName_.getByteString(i));
                    }
                    size += dataSize;
                    size += 1 * getAddressNameList().size();
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(3, data_);
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;

            @java.lang.Override
            protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(
                    com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(java.io.InputStream input)
                throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseDelimitedFrom(
                    java.io.InputStream input)
                throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(
                    com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static com.tiantiandou.serialization.UserProto.User.Address parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder(com.tiantiandou.serialization.UserProto.User.Address prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code com.tiantiandou.serialization.User.Address}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:com.tiantiandou.serialization.User.Address)
                    com.tiantiandou.serialization.UserProto.User.AddressOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                        getDescriptor() {
                    return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_Address_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                        internalGetFieldAccessorTable() {
                    return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_Address_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    com.tiantiandou.serialization.UserProto.User.Address.class,
                                    com.tiantiandou.serialization.UserProto.User.Address.Builder.class);
                }

                // Construct using com.tiantiandou.serialization.UserProto.User.Address.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    id_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    addressName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000002);
                    data_ = com.google.protobuf.ByteString.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000004);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                        getDescriptorForType() {
                    return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_Address_descriptor;
                }

                public com.tiantiandou.serialization.UserProto.User.Address getDefaultInstanceForType() {
                    return com.tiantiandou.serialization.UserProto.User.Address.getDefaultInstance();
                }

                public com.tiantiandou.serialization.UserProto.User.Address build() {
                    com.tiantiandou.serialization.UserProto.User.Address result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                public com.tiantiandou.serialization.UserProto.User.Address buildPartial() {
                    com.tiantiandou.serialization.UserProto.User.Address result = new com.tiantiandou.serialization.UserProto.User.Address(
                            this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.id_ = id_;
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        addressName_ = addressName_.getUnmodifiableView();
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.addressName_ = addressName_;
                    if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.data_ = data_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof com.tiantiandou.serialization.UserProto.User.Address) {
                        return mergeFrom((com.tiantiandou.serialization.UserProto.User.Address) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(com.tiantiandou.serialization.UserProto.User.Address other) {
                    if (other == com.tiantiandou.serialization.UserProto.User.Address.getDefaultInstance())
                        return this;
                    if (other.hasId()) {
                        setId(other.getId());
                    }
                    if (!other.addressName_.isEmpty()) {
                        if (addressName_.isEmpty()) {
                            addressName_ = other.addressName_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureAddressNameIsMutable();
                            addressName_.addAll(other.addressName_);
                        }
                        onChanged();
                    }
                    if (other.hasData()) {
                        setData(other.getData());
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    if (!hasData()) {

                        return false;
                    }
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                    com.tiantiandou.serialization.UserProto.User.Address parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (com.tiantiandou.serialization.UserProto.User.Address) e.getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private int bitField0_;

                private int id_;

                /**
                 * <code>optional int32 id = 1;</code>
                 */
                public boolean hasId() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }

                /**
                 * <code>optional int32 id = 1;</code>
                 */
                public int getId() {
                    return id_;
                }

                /**
                 * <code>optional int32 id = 1;</code>
                 */
                public Builder setId(int value) {
                    bitField0_ |= 0x00000001;
                    id_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional int32 id = 1;</code>
                 */
                public Builder clearId() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    id_ = 0;
                    onChanged();
                    return this;
                }

                private com.google.protobuf.LazyStringList addressName_ = com.google.protobuf.LazyStringArrayList.EMPTY;

                private void ensureAddressNameIsMutable() {
                    if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                        addressName_ = new com.google.protobuf.LazyStringArrayList(addressName_);
                        bitField0_ |= 0x00000002;
                    }
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public com.google.protobuf.ProtocolStringList
                        getAddressNameList() {
                    return addressName_.getUnmodifiableView();
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public int getAddressNameCount() {
                    return addressName_.size();
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public java.lang.String getAddressName(int index) {
                    return addressName_.get(index);
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public com.google.protobuf.ByteString
                        getAddressNameBytes(int index) {
                    return addressName_.getByteString(index);
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public Builder setAddressName(
                        int index, java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAddressNameIsMutable();
                    addressName_.set(index, value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public Builder addAddressName(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAddressNameIsMutable();
                    addressName_.add(value);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public Builder addAllAddressName(
                        java.lang.Iterable<java.lang.String> values) {
                    ensureAddressNameIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, addressName_);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public Builder clearAddressName() {
                    addressName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                    return this;
                }

                /**
                 * <code>repeated string address_name = 2;</code>
                 */
                public Builder addAddressNameBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAddressNameIsMutable();
                    addressName_.add(value);
                    onChanged();
                    return this;
                }

                private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

                /**
                 * <code>required bytes data = 3;</code>
                 */
                public boolean hasData() {
                    return ((bitField0_ & 0x00000004) == 0x00000004);
                }

                /**
                 * <code>required bytes data = 3;</code>
                 */
                public com.google.protobuf.ByteString getData() {
                    return data_;
                }

                /**
                 * <code>required bytes data = 3;</code>
                 */
                public Builder setData(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000004;
                    data_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>required bytes data = 3;</code>
                 */
                public Builder clearData() {
                    bitField0_ = (bitField0_ & ~0x00000004);
                    data_ = getDefaultInstance().getData();
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:com.tiantiandou.serialization.User.Address)
            }

            static {
                defaultInstance = new Address(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:com.tiantiandou.serialization.User.Address)
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private int id_;

        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private java.lang.Object name_;

        /**
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString
                getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ADDRESSES_FIELD_NUMBER = 3;
        private java.util.List<com.tiantiandou.serialization.UserProto.User.Address> addresses_;

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        public java.util.List<com.tiantiandou.serialization.UserProto.User.Address> getAddressesList() {
            return addresses_;
        }

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        public java.util.List<? extends com.tiantiandou.serialization.UserProto.User.AddressOrBuilder>
                getAddressesOrBuilderList() {
            return addresses_;
        }

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        public int getAddressesCount() {
            return addresses_.size();
        }

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        public com.tiantiandou.serialization.UserProto.User.Address getAddresses(int index) {
            return addresses_.get(index);
        }

        /**
         * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
         */
        public com.tiantiandou.serialization.UserProto.User.AddressOrBuilder getAddressesOrBuilder(
                int index) {
            return addresses_.get(index);
        }

        private void initFields() {
            id_ = 0;
            name_ = "";
            addresses_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            for (int i = 0; i < getAddressesCount(); i++) {
                if (!getAddresses(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getNameBytes());
            }
            for (int i = 0; i < addresses_.size(); i++) {
                output.writeMessage(3, addresses_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getNameBytes());
            }
            for (int i = 0; i < addresses_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, addresses_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(
                com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.tiantiandou.serialization.UserProto.User parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.tiantiandou.serialization.UserProto.User parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(
                com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.tiantiandou.serialization.UserProto.User parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.tiantiandou.serialization.UserProto.User prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.tiantiandou.serialization.User}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.tiantiandou.serialization.User)
                com.tiantiandou.serialization.UserProto.UserOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.tiantiandou.serialization.UserProto.User.class,
                                com.tiantiandou.serialization.UserProto.User.Builder.class);
            }

            // Construct using com.tiantiandou.serialization.UserProto.User.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getAddressesFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                if (addressesBuilder_ == null) {
                    addresses_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    addressesBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.tiantiandou.serialization.UserProto.internal_static_com_tiantiandou_serialization_User_descriptor;
            }

            public com.tiantiandou.serialization.UserProto.User getDefaultInstanceForType() {
                return com.tiantiandou.serialization.UserProto.User.getDefaultInstance();
            }

            public com.tiantiandou.serialization.UserProto.User build() {
                com.tiantiandou.serialization.UserProto.User result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.tiantiandou.serialization.UserProto.User buildPartial() {
                com.tiantiandou.serialization.UserProto.User result = new com.tiantiandou.serialization.UserProto.User(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                if (addressesBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        addresses_ = java.util.Collections.unmodifiableList(addresses_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.addresses_ = addresses_;
                } else {
                    result.addresses_ = addressesBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.tiantiandou.serialization.UserProto.User) {
                    return mergeFrom((com.tiantiandou.serialization.UserProto.User) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.tiantiandou.serialization.UserProto.User other) {
                if (other == com.tiantiandou.serialization.UserProto.User.getDefaultInstance())
                    return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasName()) {
                    bitField0_ |= 0x00000002;
                    name_ = other.name_;
                    onChanged();
                }
                if (addressesBuilder_ == null) {
                    if (!other.addresses_.isEmpty()) {
                        if (addresses_.isEmpty()) {
                            addresses_ = other.addresses_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureAddressesIsMutable();
                            addresses_.addAll(other.addresses_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.addresses_.isEmpty()) {
                        if (addressesBuilder_.isEmpty()) {
                            addressesBuilder_.dispose();
                            addressesBuilder_ = null;
                            addresses_ = other.addresses_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            addressesBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getAddressesFieldBuilder() : null;
                        } else {
                            addressesBuilder_.addAllMessages(other.addresses_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasName()) {

                    return false;
                }
                for (int i = 0; i < getAddressesCount(); i++) {
                    if (!getAddresses(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                com.tiantiandou.serialization.UserProto.User parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.tiantiandou.serialization.UserProto.User) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int id_;

            /**
             * <code>required int32 id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>required string name = 2;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public com.google.protobuf.ByteString
                    getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            private java.util.List<com.tiantiandou.serialization.UserProto.User.Address> addresses_ =
                    java.util.Collections.emptyList();

            private void ensureAddressesIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    addresses_ = new java.util.ArrayList<com.tiantiandou.serialization.UserProto.User.Address>(
                            addresses_);
                    bitField0_ |= 0x00000004;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.tiantiandou.serialization.UserProto.User.Address, com.tiantiandou.serialization.UserProto.User.Address.Builder, com.tiantiandou.serialization.UserProto.User.AddressOrBuilder> addressesBuilder_;

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public java.util.List<com.tiantiandou.serialization.UserProto.User.Address> getAddressesList() {
                if (addressesBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(addresses_);
                } else {
                    return addressesBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public int getAddressesCount() {
                if (addressesBuilder_ == null) {
                    return addresses_.size();
                } else {
                    return addressesBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public com.tiantiandou.serialization.UserProto.User.Address getAddresses(int index) {
                if (addressesBuilder_ == null) {
                    return addresses_.get(index);
                } else {
                    return addressesBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder setAddresses(
                    int index, com.tiantiandou.serialization.UserProto.User.Address value) {
                if (addressesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAddressesIsMutable();
                    addresses_.set(index, value);
                    onChanged();
                } else {
                    addressesBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder setAddresses(
                    int index, com.tiantiandou.serialization.UserProto.User.Address.Builder builderForValue) {
                if (addressesBuilder_ == null) {
                    ensureAddressesIsMutable();
                    addresses_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    addressesBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder addAddresses(com.tiantiandou.serialization.UserProto.User.Address value) {
                if (addressesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAddressesIsMutable();
                    addresses_.add(value);
                    onChanged();
                } else {
                    addressesBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder addAddresses(
                    int index, com.tiantiandou.serialization.UserProto.User.Address value) {
                if (addressesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAddressesIsMutable();
                    addresses_.add(index, value);
                    onChanged();
                } else {
                    addressesBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder addAddresses(
                    com.tiantiandou.serialization.UserProto.User.Address.Builder builderForValue) {
                if (addressesBuilder_ == null) {
                    ensureAddressesIsMutable();
                    addresses_.add(builderForValue.build());
                    onChanged();
                } else {
                    addressesBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder addAddresses(
                    int index, com.tiantiandou.serialization.UserProto.User.Address.Builder builderForValue) {
                if (addressesBuilder_ == null) {
                    ensureAddressesIsMutable();
                    addresses_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    addressesBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder addAllAddresses(
                    java.lang.Iterable<? extends com.tiantiandou.serialization.UserProto.User.Address> values) {
                if (addressesBuilder_ == null) {
                    ensureAddressesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, addresses_);
                    onChanged();
                } else {
                    addressesBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder clearAddresses() {
                if (addressesBuilder_ == null) {
                    addresses_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    addressesBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public Builder removeAddresses(int index) {
                if (addressesBuilder_ == null) {
                    ensureAddressesIsMutable();
                    addresses_.remove(index);
                    onChanged();
                } else {
                    addressesBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public com.tiantiandou.serialization.UserProto.User.Address.Builder getAddressesBuilder(
                    int index) {
                return getAddressesFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public com.tiantiandou.serialization.UserProto.User.AddressOrBuilder getAddressesOrBuilder(
                    int index) {
                if (addressesBuilder_ == null) {
                    return addresses_.get(index);
                } else {
                    return addressesBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public java.util.List<? extends com.tiantiandou.serialization.UserProto.User.AddressOrBuilder>
                    getAddressesOrBuilderList() {
                if (addressesBuilder_ != null) {
                    return addressesBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(addresses_);
                }
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public com.tiantiandou.serialization.UserProto.User.Address.Builder addAddressesBuilder() {
                return getAddressesFieldBuilder().addBuilder(
                        com.tiantiandou.serialization.UserProto.User.Address.getDefaultInstance());
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public com.tiantiandou.serialization.UserProto.User.Address.Builder addAddressesBuilder(
                    int index) {
                return getAddressesFieldBuilder().addBuilder(
                        index, com.tiantiandou.serialization.UserProto.User.Address.getDefaultInstance());
            }

            /**
             * <code>repeated .com.tiantiandou.serialization.User.Address addresses = 3;</code>
             */
            public java.util.List<com.tiantiandou.serialization.UserProto.User.Address.Builder>
                    getAddressesBuilderList() {
                return getAddressesFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.tiantiandou.serialization.UserProto.User.Address, com.tiantiandou.serialization.UserProto.User.Address.Builder, com.tiantiandou.serialization.UserProto.User.AddressOrBuilder>
                    getAddressesFieldBuilder() {
                if (addressesBuilder_ == null) {
                    addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.tiantiandou.serialization.UserProto.User.Address, com.tiantiandou.serialization.UserProto.User.Address.Builder, com.tiantiandou.serialization.UserProto.User.AddressOrBuilder>(
                                    addresses_,
                                    ((bitField0_ & 0x00000004) == 0x00000004),
                                    getParentForChildren(),
                                    isClean());
                    addresses_ = null;
                }
                return addressesBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:com.tiantiandou.serialization.User)
        }

        static {
            defaultInstance = new User(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.tiantiandou.serialization.User)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_tiantiandou_serialization_User_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_tiantiandou_serialization_User_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_tiantiandou_serialization_User_Address_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_tiantiandou_serialization_User_Address_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n:src/main/resources/com/tiandoudou/seri" +
                        "alization/user.proto\022\035com.tiantiandou.se" +
                        "rialization\"\233\001\n\004User\022\n\n\002id\030\001 \002(\005\022\014\n\004name" +
                        "\030\002 \002(\t\022>\n\taddresses\030\003 \003(\0132+.com.tiantian" +
                        "dou.serialization.User.Address\0329\n\007Addres" +
                        "s\022\n\n\002id\030\001 \001(\005\022\024\n\014address_name\030\002 \003(\t\022\014\n\004d" +
                        "ata\030\003 \002(\014B\013B\tUserProto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_com_tiantiandou_serialization_User_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_tiantiandou_serialization_User_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_tiantiandou_serialization_User_descriptor,
                        new java.lang.String[] { "Id", "Name", "Addresses", });
        internal_static_com_tiantiandou_serialization_User_Address_descriptor =
                internal_static_com_tiantiandou_serialization_User_descriptor.getNestedTypes().get(0);
        internal_static_com_tiantiandou_serialization_User_Address_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_tiantiandou_serialization_User_Address_descriptor,
                        new java.lang.String[] { "Id", "AddressName", "Data", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
